import type { Options } from "rehype-sanitize";

/**
 * Configure rehype-sanitize allowlist for documentation content.
 * Uses the Schema format from hast-util-sanitize (tagNames, attributes, etc.).
 */
export const sanitizeSchema: Options = {
  strip: [],
  clobber: ["id", "name"],
  clobberPrefix: "user-content-",
  tagNames: [
    "a",
    "abbr",
    "b",
    "blockquote",
    "br",
    "caption",
    "code",
    "col",
    "colgroup",
    "dd",
    "del",
    "details",
    "dfn",
    "div",
    "dl",
    "dt",
    "em",
    "figcaption",
    "figure",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "img",
    "ins",
    "kbd",
    "li",
    "mark",
    "ol",
    "p",
    "pre",
    "q",
    "s",
    "samp",
    "section",
    "small",
    "span",
    "strong",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "time",
    "tr",
    "u",
    "ul",
    "var"
  ],
  attributes: {
    "*": ["className", "id", "lang"],
    a: ["href", "target", "rel", "title", "ariaLabel", "aria-label"],
    img: ["src", "alt", "title", "width", "height", "loading"],
    code: ["className"],
    pre: ["className"],
    td: ["colSpan", "rowSpan"],
    th: ["colSpan", "rowSpan", "scope"],
    time: ["dateTime"],
    col: ["span"],
    colgroup: ["span"],
    details: ["open"],
    del: ["cite", "dateTime"],
    ins: ["cite", "dateTime"],
    q: ["cite"],
    dfn: ["title"],
    abbr: ["title"]
  }
} as const satisfies Options;
